### ISSUE TITLE
Problems with some tutorials

### ISSUE THREAD

**Issue by IaroslavElistratov** [themis-ai/capsa#123]
- tutorials 1 and 2 don't open because their name changed [here](https://github.com/themis-ai/capsa/tree/main/notebooks) but our API site still tries to open the old name [here](https://themisai.io/capsa/tutorials/index.html)
- tutorial 4 doesn’t run due to a small typo (variable name)
- please add the introduction and the faces tutorial to the site as well

<img width="1312" alt="Screenshot 2023-04-22 at 10 33 39 PM" src="https://user-images.githubusercontent.com/57019863/233803167-0b8cce83-6f9e-4746-98bf-e0c84041d504.png">

**Comment by egesko** [comment]
Currently, the docs are not being compiled and pushed correctly due to a permission error in a Github Action. @aamini could you look into updating repo permission settings so that it can be pushed correctly, or give Iaro or I some of the admin permissions so that we can update repo settings accordingly.

**Comment by egesko** [comment]
Completed!
